-- Librélula · Esperados del catálogo
-- Ejecutar en Supabase > SQL Editor antes de aplicar el rediseño editorial.
-- No borra ni modifica libros, ediciones, reseñas o bibliotecas existentes.

begin;

create table if not exists public.book_release_alerts (
  id bigint generated by default as identity primary key,
  legacy_user_id bigint not null references public.profiles(legacy_id) on delete cascade,
  edition_id uuid not null references public.book_editions(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (legacy_user_id, edition_id)
);

create index if not exists book_release_alerts_user_idx
  on public.book_release_alerts (legacy_user_id, created_at desc);

create index if not exists book_release_alerts_edition_idx
  on public.book_release_alerts (edition_id);

alter table public.book_release_alerts enable row level security;

drop policy if exists book_release_alerts_select_own on public.book_release_alerts;
create policy book_release_alerts_select_own
on public.book_release_alerts
for select
to authenticated
using (legacy_user_id = public.current_legacy_user_id());

drop policy if exists book_release_alerts_insert_own on public.book_release_alerts;
create policy book_release_alerts_insert_own
on public.book_release_alerts
for insert
to authenticated
with check (legacy_user_id = public.current_legacy_user_id());

drop policy if exists book_release_alerts_delete_own on public.book_release_alerts;
create policy book_release_alerts_delete_own
on public.book_release_alerts
for delete
to authenticated
using (legacy_user_id = public.current_legacy_user_id());

grant select, insert, delete on public.book_release_alerts to authenticated;
grant usage, select on sequence public.book_release_alerts_id_seq to authenticated;

commit;

-- Comprobación final. Debe devolver las columnas tabla y alertas_actuales.
select
  to_regclass('public.book_release_alerts') as tabla,
  (select count(*) from public.book_release_alerts) as alertas_actuales;
