-- Inicio social y estadísticas lectoras de Librélula.
-- Idempotente: puede ejecutarse más de una vez.

create extension if not exists pgcrypto;

create table if not exists public.reading_weekly_goals (
  legacy_user_id bigint primary key references public.legacy_users(legacy_id) on delete cascade,
  page_goal integer not null default 150 check (page_goal between 1 and 10000),
  updated_at timestamptz not null default now()
);

create table if not exists public.reading_progress_log (
  id bigint generated by default as identity primary key,
  legacy_user_id bigint not null references public.legacy_users(legacy_id) on delete cascade,
  book_id text not null references public.books(id) on delete cascade,
  previous_progress integer not null default 0 check (previous_progress between 0 and 100),
  new_progress integer not null default 0 check (new_progress between 0 and 100),
  pages_delta integer not null default 0 check (pages_delta >= 0),
  created_at timestamptz not null default now()
);

create index if not exists reading_progress_log_user_date_idx
  on public.reading_progress_log(legacy_user_id, created_at desc);

create index if not exists reading_progress_log_book_date_idx
  on public.reading_progress_log(book_id, created_at desc);

create table if not exists public.reader_posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 1200),
  book_id text references public.books(id) on delete set null,
  spoiler boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists reader_posts_created_at_idx
  on public.reader_posts(created_at desc);

create table if not exists public.reader_activity_likes (
  activity_key text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (activity_key, user_id)
);

create index if not exists reader_activity_likes_key_idx
  on public.reader_activity_likes(activity_key);

create table if not exists public.reader_activity_comments (
  id uuid primary key default gen_random_uuid(),
  activity_key text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists reader_activity_comments_key_date_idx
  on public.reader_activity_comments(activity_key, created_at);

alter table public.reading_weekly_goals enable row level security;
alter table public.reading_progress_log enable row level security;
alter table public.reader_posts enable row level security;
alter table public.reader_activity_likes enable row level security;
alter table public.reader_activity_comments enable row level security;

drop policy if exists "weekly goals own select" on public.reading_weekly_goals;
create policy "weekly goals own select"
  on public.reading_weekly_goals
  for select
  to authenticated
  using (legacy_user_id = public.current_legacy_user_id());

drop policy if exists "weekly goals own insert" on public.reading_weekly_goals;
create policy "weekly goals own insert"
  on public.reading_weekly_goals
  for insert
  to authenticated
  with check (legacy_user_id = public.current_legacy_user_id());

drop policy if exists "weekly goals own update" on public.reading_weekly_goals;
create policy "weekly goals own update"
  on public.reading_weekly_goals
  for update
  to authenticated
  using (legacy_user_id = public.current_legacy_user_id())
  with check (legacy_user_id = public.current_legacy_user_id());

drop policy if exists "reading progress authenticated read" on public.reading_progress_log;
create policy "reading progress authenticated read"
  on public.reading_progress_log
  for select
  to authenticated
  using (true);

drop policy if exists "reading progress own insert" on public.reading_progress_log;
create policy "reading progress own insert"
  on public.reading_progress_log
  for insert
  to authenticated
  with check (legacy_user_id = public.current_legacy_user_id());

drop policy if exists "reader posts authenticated read" on public.reader_posts;
create policy "reader posts authenticated read"
  on public.reader_posts
  for select
  to authenticated
  using (true);

drop policy if exists "reader posts own insert" on public.reader_posts;
create policy "reader posts own insert"
  on public.reader_posts
  for insert
  to authenticated
  with check (author_id = auth.uid());

drop policy if exists "reader posts own delete" on public.reader_posts;
create policy "reader posts own delete"
  on public.reader_posts
  for delete
  to authenticated
  using (author_id = auth.uid());

drop policy if exists "activity likes authenticated read" on public.reader_activity_likes;
create policy "activity likes authenticated read"
  on public.reader_activity_likes
  for select
  to authenticated
  using (true);

drop policy if exists "activity likes own insert" on public.reader_activity_likes;
create policy "activity likes own insert"
  on public.reader_activity_likes
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "activity likes own delete" on public.reader_activity_likes;
create policy "activity likes own delete"
  on public.reader_activity_likes
  for delete
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "activity comments authenticated read" on public.reader_activity_comments;
create policy "activity comments authenticated read"
  on public.reader_activity_comments
  for select
  to authenticated
  using (true);

drop policy if exists "activity comments own insert" on public.reader_activity_comments;
create policy "activity comments own insert"
  on public.reader_activity_comments
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "activity comments own delete" on public.reader_activity_comments;
create policy "activity comments own delete"
  on public.reader_activity_comments
  for delete
  to authenticated
  using (user_id = auth.uid());

insert into public.reading_weekly_goals(legacy_user_id, page_goal)
select legacy_id, 150
from public.legacy_users
on conflict (legacy_user_id) do nothing;

select
  (select count(*) from public.reading_weekly_goals) as metas_semanales,
  (select count(*) from public.reading_progress_log) as sesiones_registradas,
  (select count(*) from public.reader_posts) as publicaciones,
  (select count(*) from public.reader_activity_likes) as me_gusta,
  (select count(*) from public.reader_activity_comments) as comentarios;
