-- Librélula · Clubes de lectura V2
-- Ejecutar después de reading-clubs.sql.
-- Añade gestión real del club sin borrar conversaciones ni miembros existentes.

create extension if not exists pgcrypto;

alter table public.reading_clubs
  add column if not exists rules text[] not null default array[
    'Respeta el modo sin spoilers.',
    'Marca los spoilers siempre.',
    'Comparte con amabilidad y empatía.'
  ]::text[];

alter table public.reading_club_members
  add column if not exists current_page integer not null default 0;

alter table public.reading_club_members
  drop constraint if exists reading_club_members_current_page_check;
alter table public.reading_club_members
  add constraint reading_club_members_current_page_check check (current_page >= 0);

alter table public.reading_club_meetings
  add column if not exists event_type text not null default 'meeting',
  add column if not exists ends_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

alter table public.reading_club_meetings
  drop constraint if exists reading_club_meetings_event_type_check;
alter table public.reading_club_meetings
  add constraint reading_club_meetings_event_type_check
  check (event_type in ('meeting', 'reading', 'debate', 'deadline', 'other'));

create table if not exists public.reading_club_meeting_attendance (
  meeting_id bigint not null references public.reading_club_meetings(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  response text not null default 'going' check (response in ('going', 'maybe', 'not_going')),
  responded_at timestamptz not null default now(),
  primary key (meeting_id, user_id)
);

-- La estructura queda lista para los marcapáginas/logros que Sofía diseñe más adelante.
-- Al abandonar el club se eliminan automáticamente por la clave foránea compuesta.
create table if not exists public.reading_club_member_achievements (
  id bigint generated by default as identity primary key,
  club_id bigint not null,
  user_id uuid not null,
  badge_key text not null,
  label text not null,
  description text not null default '',
  image_url text not null default '',
  awarded_at timestamptz not null default now(),
  unique (club_id, user_id, badge_key),
  foreign key (club_id, user_id)
    references public.reading_club_members(club_id, user_id)
    on delete cascade
);

create index if not exists reading_club_achievements_user_idx
  on public.reading_club_member_achievements (user_id, awarded_at desc);
create index if not exists reading_club_meeting_attendance_user_idx
  on public.reading_club_meeting_attendance (user_id, responded_at desc);

-- Evita que una actualización directa cambie la autoría del club.
create or replace function public.reading_club_protect_owner()
returns trigger
language plpgsql
as $$
begin
  if new.owner_id is distinct from old.owner_id then
    raise exception 'La autoría del club no puede cambiarse desde esta operación.';
  end if;
  return new;
end;
$$;

drop trigger if exists reading_club_protect_owner_before_update on public.reading_clubs;
create trigger reading_club_protect_owner_before_update
before update on public.reading_clubs
for each row execute function public.reading_club_protect_owner();

-- Mantiene updated_at en reuniones.
drop trigger if exists reading_club_meetings_touch_updated_at on public.reading_club_meetings;
create trigger reading_club_meetings_touch_updated_at
before update on public.reading_club_meetings
for each row execute function public.reading_club_touch_updated_at();

create or replace function public.update_reading_club_progress(
  p_club_id bigint,
  p_current_chapter integer,
  p_current_page integer,
  p_progress integer default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total_pages integer := 0;
  v_safe_page integer;
  v_safe_progress integer;
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión.';
  end if;

  select greatest(0, coalesce(b.pages, 0))
    into v_total_pages
  from public.reading_clubs c
  left join public.books b on b.id = c.current_book_id
  where c.id = p_club_id;

  v_safe_page := greatest(0, coalesce(p_current_page, 0));
  if v_total_pages > 0 then
    v_safe_page := least(v_safe_page, v_total_pages);
    v_safe_progress := round((v_safe_page::numeric / v_total_pages::numeric) * 100)::integer;
  else
    v_safe_progress := greatest(0, least(100, coalesce(p_progress, 0)));
  end if;

  update public.reading_club_members
  set current_chapter = greatest(1, coalesce(p_current_chapter, 1)),
      current_page = v_safe_page,
      progress = v_safe_progress,
      updated_at = now()
  where club_id = p_club_id
    and user_id = auth.uid()
    and status = 'active';

  if not found then
    raise exception 'No perteneces a este club.';
  end if;

  return true;
end;
$$;

create or replace function public.set_reading_club_member_role(
  p_club_id bigint,
  p_user_id uuid,
  p_role text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner uuid;
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión.';
  end if;

  select owner_id into v_owner from public.reading_clubs where id = p_club_id;
  if v_owner is null then raise exception 'El club no existe.'; end if;
  if v_owner <> auth.uid() then
    raise exception 'Solo la creadora puede gestionar moderadoras.';
  end if;
  if p_user_id = v_owner then
    raise exception 'La creadora conserva siempre su rol.';
  end if;
  if p_role not in ('moderator', 'member') then
    raise exception 'El rol no es válido.';
  end if;

  update public.reading_club_members
  set role = p_role, updated_at = now()
  where club_id = p_club_id
    and user_id = p_user_id
    and status = 'active';

  if not found then raise exception 'La persona no pertenece al club.'; end if;
  return true;
end;
$$;

create or replace function public.remove_reading_club_member(
  p_club_id bigint,
  p_user_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner uuid;
  v_actor_role text;
begin
  if auth.uid() is null then raise exception 'Debes iniciar sesión.'; end if;

  select owner_id into v_owner from public.reading_clubs where id = p_club_id;
  select role into v_actor_role
  from public.reading_club_members
  where club_id = p_club_id and user_id = auth.uid() and status = 'active';

  if v_actor_role not in ('owner', 'moderator') then
    raise exception 'No tienes permisos para retirar miembros.';
  end if;
  if p_user_id = v_owner then
    raise exception 'La creadora no puede ser expulsada del club.';
  end if;
  if v_actor_role = 'moderator' and exists (
    select 1 from public.reading_club_members
    where club_id = p_club_id and user_id = p_user_id and role = 'moderator'
  ) then
    raise exception 'Solo la creadora puede retirar a otra moderadora.';
  end if;

  delete from public.reading_club_members
  where club_id = p_club_id and user_id = p_user_id;
  return true;
end;
$$;

create or replace function public.delete_reading_club(p_club_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Debes iniciar sesión.'; end if;
  delete from public.reading_clubs
  where id = p_club_id and owner_id = auth.uid();
  if not found then raise exception 'Solo la creadora puede eliminar el club.'; end if;
  return true;
end;
$$;

create or replace function public.update_reading_club_settings(
  p_club_id bigint,
  p_name text,
  p_description text,
  p_visibility text,
  p_banner_url text,
  p_icon_url text,
  p_rules text[]
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Debes iniciar sesión.'; end if;
  if not public.is_reading_club_admin(p_club_id, auth.uid()) then
    raise exception 'No tienes permisos para editar este club.';
  end if;

  update public.reading_clubs
  set name = left(trim(coalesce(p_name, name)), 80),
      description = trim(coalesce(p_description, description)),
      visibility = case when p_visibility = 'private' then 'private' else 'public' end,
      banner_url = trim(coalesce(p_banner_url, banner_url)),
      icon_url = trim(coalesce(p_icon_url, icon_url)),
      rules = array(
        select left(trim(item.rule), 240)
        from unnest(coalesce(p_rules, array[]::text[])) as item(rule)
        where trim(item.rule) <> ''
        limit 12
      ),
      updated_at = now()
  where id = p_club_id;

  return true;
end;
$$;

-- La política antigua permitía que un miembro alterase su propio rol.
drop policy if exists reading_club_members_update on public.reading_club_members;
create policy reading_club_members_update
on public.reading_club_members for update
to authenticated
using (public.is_reading_club_admin(club_id, auth.uid()))
with check (public.is_reading_club_admin(club_id, auth.uid()));

drop policy if exists reading_club_members_delete on public.reading_club_members;
create policy reading_club_members_delete
on public.reading_club_members for delete
to authenticated
using (
  (user_id = auth.uid() and role <> 'owner')
  or (public.is_reading_club_admin(club_id, auth.uid()) and role <> 'owner')
);

alter table public.reading_club_meeting_attendance enable row level security;
alter table public.reading_club_member_achievements enable row level security;

drop policy if exists reading_club_attendance_select on public.reading_club_meeting_attendance;
create policy reading_club_attendance_select
on public.reading_club_meeting_attendance for select
to authenticated
using (
  exists (
    select 1 from public.reading_club_meetings m
    where m.id = meeting_id and public.is_reading_club_member(m.club_id, auth.uid())
  )
);

drop policy if exists reading_club_attendance_manage on public.reading_club_meeting_attendance;
create policy reading_club_attendance_manage
on public.reading_club_meeting_attendance for all
to authenticated
using (user_id = auth.uid())
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.reading_club_meetings m
    where m.id = meeting_id and public.is_reading_club_member(m.club_id, auth.uid())
  )
);

drop policy if exists reading_club_achievements_select on public.reading_club_member_achievements;
create policy reading_club_achievements_select
on public.reading_club_member_achievements for select
to authenticated
using (
  user_id = auth.uid()
  or public.is_reading_club_member(club_id, auth.uid())
);

drop policy if exists reading_club_achievements_manage on public.reading_club_member_achievements;
create policy reading_club_achievements_manage
on public.reading_club_member_achievements for all
to authenticated
using (public.is_reading_club_admin(club_id, auth.uid()))
with check (public.is_reading_club_admin(club_id, auth.uid()));

grant execute on function public.update_reading_club_progress(bigint, integer, integer, integer) to authenticated;
grant execute on function public.set_reading_club_member_role(bigint, uuid, text) to authenticated;
grant execute on function public.remove_reading_club_member(bigint, uuid) to authenticated;
grant execute on function public.delete_reading_club(bigint) to authenticated;
grant execute on function public.update_reading_club_settings(bigint, text, text, text, text, text, text[]) to authenticated;

grant select, insert, update, delete on public.reading_club_meeting_attendance to authenticated;
grant select, insert, update, delete on public.reading_club_member_achievements to authenticated;
grant usage, select on sequence public.reading_club_member_achievements_id_seq to authenticated;

select
  exists(
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'reading_club_members' and column_name = 'current_page'
  ) as progreso_por_paginas,
  exists(
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'reading_clubs' and column_name = 'rules'
  ) as normas_editables,
  to_regclass('public.reading_club_meeting_attendance') is not null as calendario_real,
  to_regclass('public.reading_club_member_achievements') is not null as marcapaginas_preparados,
  to_regprocedure('public.set_reading_club_member_role(bigint,uuid,text)') is not null as roles_seguros;
