-- LibrÃ©lula Â· Clubes V12
-- Historial de lecturas del club, cambio seguro de libro y estanterÃ­a con reseÃ±as enlazadas.
-- Requiere Clubes V1-V5. Compatible con V9/V10/V11.
-- No borra libros, reseÃ±as, mensajes ni miembros.

begin;

create table if not exists public.reading_club_readings (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.reading_clubs(id) on delete cascade,
  book_id text not null references public.books(id) on delete restrict,
  status text not null default 'current' check (status in ('current', 'completed')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  closed_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (status = 'current' and finished_at is null)
    or (status = 'completed' and finished_at is not null)
  )
);

create unique index if not exists reading_club_one_current_reading_idx
  on public.reading_club_readings (club_id)
  where status = 'current';

create index if not exists reading_club_readings_history_idx
  on public.reading_club_readings (club_id, finished_at desc)
  where status = 'completed';

create table if not exists public.reading_club_reading_members (
  reading_id bigint not null references public.reading_club_readings(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role_at_close text not null default 'member' check (role_at_close in ('owner', 'moderator', 'member')),
  progress_at_close integer not null default 0 check (progress_at_close between 0 and 100),
  current_page_at_close integer not null default 0 check (current_page_at_close >= 0),
  current_chapter_at_close integer not null default 1 check (current_chapter_at_close >= 1),
  captured_at timestamptz not null default now(),
  primary key (reading_id, user_id)
);

create index if not exists reading_club_reading_members_user_idx
  on public.reading_club_reading_members (user_id, reading_id);

alter table public.reading_clubs
  add column if not exists current_reading_id bigint;

alter table public.reading_clubs
  drop constraint if exists reading_clubs_current_reading_fk;
alter table public.reading_clubs
  add constraint reading_clubs_current_reading_fk
  foreign key (current_reading_id)
  references public.reading_club_readings(id)
  on delete set null;

alter table public.reading_club_posts
  add column if not exists reading_id bigint;

alter table public.reading_club_posts
  drop constraint if exists reading_club_posts_reading_fk;
alter table public.reading_club_posts
  add constraint reading_club_posts_reading_fk
  foreign key (reading_id)
  references public.reading_club_readings(id)
  on delete set null;

create index if not exists reading_club_posts_reading_idx
  on public.reading_club_posts (club_id, reading_id, channel, chapter_number, created_at desc);

-- Backfill: cada club existente recibe un ciclo de lectura actual.
insert into public.reading_club_readings (club_id, book_id, status, started_at)
select c.id, c.current_book_id, 'current', coalesce(c.created_at, now())
from public.reading_clubs c
where c.current_book_id is not null
  and not exists (
    select 1
    from public.reading_club_readings r
    where r.club_id = c.id and r.status = 'current'
  );

update public.reading_clubs c
set current_reading_id = r.id
from public.reading_club_readings r
where r.club_id = c.id
  and r.status = 'current'
  and c.current_reading_id is distinct from r.id;

update public.reading_club_posts p
set reading_id = c.current_reading_id
from public.reading_clubs c
where c.id = p.club_id
  and p.reading_id is null
  and c.current_reading_id is not null;

create or replace function public.reading_club_reading_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists reading_club_readings_touch_updated_at on public.reading_club_readings;
create trigger reading_club_readings_touch_updated_at
before update on public.reading_club_readings
for each row execute function public.reading_club_reading_touch_updated_at();

-- Todo mensaje nuevo queda asociado automÃ¡ticamente a la lectura vigente.
create or replace function public.reading_club_attach_current_reading()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.reading_id is null then
    select c.current_reading_id into new.reading_id
    from public.reading_clubs c
    where c.id = new.club_id;
  end if;
  return new;
end;
$$;

drop trigger if exists reading_club_posts_attach_current_reading on public.reading_club_posts;
create trigger reading_club_posts_attach_current_reading
before insert on public.reading_club_posts
for each row execute function public.reading_club_attach_current_reading();

alter table public.reading_club_readings enable row level security;
alter table public.reading_club_reading_members enable row level security;

revoke insert, update, delete on public.reading_club_readings from authenticated;
revoke insert, update, delete on public.reading_club_reading_members from authenticated;
grant select on public.reading_club_readings to authenticated;
grant select on public.reading_club_reading_members to authenticated;

drop policy if exists reading_club_readings_select on public.reading_club_readings;
create policy reading_club_readings_select
on public.reading_club_readings
for select
to authenticated
using (
  exists (
    select 1
    from public.reading_clubs c
    where c.id = club_id
      and (
        c.visibility = 'public'
        or exists (
          select 1
          from public.reading_club_members m
          where m.club_id = c.id
            and m.user_id = auth.uid()
            and m.status = 'active'
        )
      )
  )
);

drop policy if exists reading_club_reading_members_select on public.reading_club_reading_members;
create policy reading_club_reading_members_select
on public.reading_club_reading_members
for select
to authenticated
using (
  exists (
    select 1
    from public.reading_club_readings r
    join public.reading_clubs c on c.id = r.club_id
    where r.id = reading_id
      and (
        c.visibility = 'public'
        or exists (
          select 1
          from public.reading_club_members m
          where m.club_id = c.id
            and m.user_id = auth.uid()
            and m.status = 'active'
        )
      )
  )
);

-- EstanterÃ­a: las reseÃ±as NO se duplican. Se consultan en vivo desde user_books,
-- exactamente la misma fuente que utiliza la ficha del libro.
create or replace function public.reading_club_bookshelf(p_club_id bigint)
returns table (
  reading_id bigint,
  reading_status text,
  book_id text,
  book_title text,
  book_author text,
  book_cover text,
  book_pages integer,
  started_at timestamptz,
  finished_at timestamptz,
  participant_count integer,
  rating_count integer,
  review_count integer,
  avg_rating numeric,
  reviews jsonb
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesiÃ³n.';
  end if;

  if not exists (
    select 1
    from public.reading_clubs c
    where c.id = p_club_id
      and (
        c.visibility = 'public'
        or exists (
          select 1
          from public.reading_club_members m
          where m.club_id = c.id
            and m.user_id = auth.uid()
            and m.status = 'active'
        )
      )
  ) then
    raise exception 'No tienes acceso a la estanterÃ­a de este club.';
  end if;

  return query
  select
    r.id,
    r.status,
    r.book_id,
    b.title,
    b.author,
    b.cover,
    b.pages,
    r.started_at,
    r.finished_at,
    case
      when r.status = 'current' then (
        select count(*)::integer
        from public.reading_club_members cm
        where cm.club_id = r.club_id and cm.status = 'active'
      )
      else (
        select count(*)::integer
        from public.reading_club_reading_members rm
        where rm.reading_id = r.id
      )
    end as participant_count,
    case
      when r.status = 'completed' then (
        select count(*)::integer
        from public.reading_club_reading_members rm
        join public.profiles p on p.id = rm.user_id
        join public.user_books ub
          on ub.legacy_user_id = p.legacy_id
         and ub.book_id = r.book_id
        where rm.reading_id = r.id
          and ub.score between 1 and 5
      )
      else 0
    end as rating_count,
    case
      when r.status = 'completed' then (
        select count(*)::integer
        from public.reading_club_reading_members rm
        join public.profiles p on p.id = rm.user_id
        join public.user_books ub
          on ub.legacy_user_id = p.legacy_id
         and ub.book_id = r.book_id
        where rm.reading_id = r.id
          and trim(coalesce(ub.notes, '')) <> ''
      )
      else 0
    end as review_count,
    case
      when r.status = 'completed' then (
        select round(avg(ub.score)::numeric, 2)
        from public.reading_club_reading_members rm
        join public.profiles p on p.id = rm.user_id
        join public.user_books ub
          on ub.legacy_user_id = p.legacy_id
         and ub.book_id = r.book_id
        where rm.reading_id = r.id
          and ub.score between 1 and 5
      )
      else null
    end as avg_rating,
    case
      when r.status = 'completed' then coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'profile_id', p.id,
            'score', case when ub.score between 1 and 5 then ub.score else null end,
            'review', trim(coalesce(ub.notes, '')),
            'finished_at', ub.finished_at,
            'updated_at', ub.updated_at
          )
          order by ub.updated_at desc nulls last, ub.finished_at desc nulls last
        )
        from public.reading_club_reading_members rm
        join public.profiles p on p.id = rm.user_id
        join public.user_books ub
          on ub.legacy_user_id = p.legacy_id
         and ub.book_id = r.book_id
        where rm.reading_id = r.id
          and (
            ub.score between 1 and 5
            or trim(coalesce(ub.notes, '')) <> ''
          )
      ), '[]'::jsonb)
      else '[]'::jsonb
    end as reviews
  from public.reading_club_readings r
  join public.books b on b.id = r.book_id
  where r.club_id = p_club_id
  order by
    case when r.status = 'current' then 0 else 1 end,
    r.finished_at desc nulls first,
    r.started_at desc;
end;
$$;

-- Cierra la lectura actual y empieza otra de forma atÃ³mica.
-- Solo la creadora puede cambiar el libro del club, igual que en V3/V4.
create or replace function public.finish_reading_club_book(
  p_club_id bigint,
  p_next_book_id text,
  p_next_chapters jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_club public.reading_clubs%rowtype;
  v_current_reading_id bigint;
  v_new_reading_id bigint;
  v_item record;
  v_count integer := 0;
  v_title text;
  v_end_page integer;
  v_previous_page integer := 0;
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesiÃ³n.';
  end if;

  select * into v_club
  from public.reading_clubs
  where id = p_club_id
  for update;

  if not found then
    raise exception 'El club no existe.';
  end if;

  if v_club.owner_id is distinct from auth.uid() then
    raise exception 'Solo la creadora puede cerrar una lectura y elegir el siguiente libro.';
  end if;

  if v_club.current_book_id is null then
    raise exception 'El club no tiene una lectura activa.';
  end if;

  if trim(coalesce(p_next_book_id, '')) = '' then
    raise exception 'Elige el siguiente libro del club.';
  end if;

  if p_next_book_id = v_club.current_book_id then
    raise exception 'Elige un libro distinto para la siguiente lectura.';
  end if;

  if not exists (select 1 from public.books b where b.id = p_next_book_id) then
    raise exception 'El siguiente libro no existe en el catÃ¡logo.';
  end if;

  if jsonb_typeof(coalesce(p_next_chapters, '[]'::jsonb)) <> 'array'
     or jsonb_array_length(coalesce(p_next_chapters, '[]'::jsonb)) < 1 then
    raise exception 'AÃ±ade al menos un capÃ­tulo para la nueva lectura.';
  end if;

  v_current_reading_id := v_club.current_reading_id;

  if v_current_reading_id is null then
    select r.id into v_current_reading_id
    from public.reading_club_readings r
    where r.club_id = p_club_id and r.status = 'current'
    limit 1;
  end if;

  if v_current_reading_id is null then
    insert into public.reading_club_readings (club_id, book_id, status, started_at)
    values (p_club_id, v_club.current_book_id, 'current', coalesce(v_club.created_at, now()))
    returning id into v_current_reading_id;
  end if;

  -- Snapshot de quiÃ©n compartiÃ³ esta lectura. Las reseÃ±as siguen enlazadas en vivo.
  insert into public.reading_club_reading_members (
    reading_id,
    user_id,
    role_at_close,
    progress_at_close,
    current_page_at_close,
    current_chapter_at_close
  )
  select
    v_current_reading_id,
    m.user_id,
    m.role,
    greatest(0, least(100, coalesce(m.progress, 0))),
    greatest(0, coalesce(m.current_page, 0)),
    greatest(1, coalesce(m.current_chapter, 1))
  from public.reading_club_members m
  where m.club_id = p_club_id
    and m.status = 'active'
  on conflict (reading_id, user_id) do update
    set role_at_close = excluded.role_at_close,
        progress_at_close = excluded.progress_at_close,
        current_page_at_close = excluded.current_page_at_close,
        current_chapter_at_close = excluded.current_chapter_at_close,
        captured_at = now();

  update public.reading_club_readings
  set status = 'completed',
      finished_at = now(),
      closed_by = auth.uid(),
      updated_at = now()
  where id = v_current_reading_id;

  insert into public.reading_club_readings (club_id, book_id, status, started_at)
  values (p_club_id, p_next_book_id, 'current', now())
  returning id into v_new_reading_id;

  update public.reading_clubs
  set current_book_id = p_next_book_id,
      current_reading_id = v_new_reading_id,
      reading_plan_enabled = false,
      reading_plan_unlocked_chapter = 1,
      reading_plan_next_unlock_at = null,
      updated_at = now()
  where id = p_club_id;

  -- Nueva lectura = nuevo progreso del club. No modificamos ni damos por terminadas
  -- las bibliotecas personales de otras personas.
  update public.reading_club_members
  set current_chapter = 1,
      current_page = 0,
      progress = 0,
      updated_at = now()
  where club_id = p_club_id
    and status = 'active';

  delete from public.reading_club_chapters where club_id = p_club_id;

  for v_item in
    select value, ordinality
    from jsonb_array_elements(coalesce(p_next_chapters, '[]'::jsonb)) with ordinality
  loop
    v_count := v_count + 1;
    if v_count > 160 then exit; end if;

    v_title := left(trim(coalesce(v_item.value->>'title', 'CapÃ­tulo ' || v_count)), 180);
    if v_title = '' then v_title := 'CapÃ­tulo ' || v_count; end if;

    begin
      v_end_page := nullif(trim(coalesce(v_item.value->>'end_page', '')), '')::integer;
    exception when invalid_text_representation then
      raise exception 'La pÃ¡gina final del capÃ­tulo % no es vÃ¡lida.', v_count;
    end;

    if v_end_page is not null then
      if v_end_page < 1 or v_end_page <= v_previous_page then
        raise exception 'Las pÃ¡ginas finales deben crecer de un capÃ­tulo al siguiente.';
      end if;
      v_previous_page := v_end_page;
    end if;

    insert into public.reading_club_chapters
      (club_id, chapter_number, title, end_page, created_by)
    values
      (p_club_id, v_count, v_title, v_end_page, auth.uid());
  end loop;

  if v_count = 0 then
    raise exception 'AÃ±ade al menos un capÃ­tulo.';
  end if;

  return v_current_reading_id;
end;
$$;

grant execute on function public.reading_club_bookshelf(bigint) to authenticated;
grant execute on function public.finish_reading_club_book(bigint, text, jsonb) to authenticated;
revoke execute on function public.reading_club_bookshelf(bigint) from anon;
revoke execute on function public.finish_reading_club_book(bigint, text, jsonb) from anon;

commit;

-- ComprobaciÃ³n V12: los seis indicadores deben ser true.
select
  to_regclass('public.reading_club_readings') is not null as historial_creado,
  to_regclass('public.reading_club_reading_members') is not null as participantes_guardados,
  exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'reading_club_posts' and column_name = 'reading_id'
  ) as conversaciones_separadas_por_lectura,
  to_regprocedure('public.reading_club_bookshelf(bigint)') is not null as estanteria_disponible,
  to_regprocedure('public.finish_reading_club_book(bigint,text,jsonb)') is not null as cierre_de_lectura_disponible,
  not has_function_privilege('anon', 'public.finish_reading_club_book(bigint,text,jsonb)', 'EXECUTE') as cierre_bloqueado_para_anon;


